config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get '/'            => 'static_pages#home',        as: 'home'
  get '/leaderboard' => 'static_pages#leaderboard', as: 'leaderboard'

  resources :questions, only: [:index, :create, :show]
  resources :answers, only: [:create]

  devise_for :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

end

app/models/question.rb
class Question < ActiveRecord::Base
  include HTTParty
  base_uri "http://jservice.io"
  format :json

  has_many :answers
  has_many :users, through: :answers

  validates :question_id, uniqueness: true
  validates_presence_of :value

  # 'popular' categories
  CATEGORIES = [306, 1, 136, 42, 780, 21, 105, 25, 7, 103, 442, 67, 109, 227, 114, 31, 176, 582, 508, 49, 561, 1114, 223, 770, 622, 313, 420, 253, 83, 184, 211, 51, 539, 267, 357, 530, 793, 369, 777, 672, 78, 574, 680, 50, 99, 309, 41, 249, 26, 218, 1420, 1145, 1079, 37, 89, 139, 197, 17, 897, 1800, 705, 1195, 128, 2537]

  def self.generate_board(user_id)
    questions = []
    answered = User.find(user_id).answered
    qids = Question.all.pluck(:category_id).uniq
    while questions.count < 20
      q = Question.where(category_id: qids.sample).sample 
      questions << q unless answered.include?(q.id)
    end
    questions.sort! { |x, y| x.value <=> y.value }
  end

  def self.cache_questions_by_category(category_id=nil)
    category_id = CATEGORIES.sample if category_id.nil?
    request = get("/api/category?id=#{category_id}")
    request["clues"].each do |clue|
      Question.where(question_id: clue["id"]).first_or_create! do |q|
        q.answer          = clue["answer"]
        q.question        = clue["question"]
        q.question_id     = clue["id"]
        q.value           = clue["value"] || 500
        q.category_title  = request["title"]
        q.category_id     = request["id"]
        q.airdate         = clue["airdate"].first(10)
      end
    end
  end

  def self.cache_random_question(count = 1)
    request = get("/api/random?count=#{count}")
    request.each do |r|
      Question.where(question_id: r["id"]).first_or_create! do |q|
        q.answer          = r["answer"]
        q.question        = r["question"]
        q.question_id     = r["id"]
        q.value           = r["value"] || 500
        q.category_title  = r["category"]["title"]
        q.category_id     = r["category"]["id"]
        q.airdate         = r["airdate"].first(10)
      end
    end
  end

  def self.remove_html_from_answers
    questions = Question.where("answer LIKE (?)", "%<i>%")
    questions.each do |q|
      q.update(answer: q.answer.gsub("<i>", ""))
      q.update(answer: q.answer.gsub!("</i>", ""))
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  paginates_per 10

  has_many :answers
  has_many :questions, through: :answers

  def self.fetch_leaderboard
    leaderboard = {}
    User.all.each do |u|
      leaderboard["#{u.username}"] = u.total_score
    end
    leaderboard.sort { |x, y| y[1] <=> x[1] }
  end

  def answer_question q_id
    self.answers.where(question_id: q_id).first_or_create!
  end

  def answered?(q_id)
    self.answered.include?(q_id.to_i)
  end

  def answered
    self.answers.pluck(:question_id)
  end

  def total_score
    total_score = 0
    correct_answers.each do |q|
      total_score += Question.find(q).value
    end
    wrong_answers.each do |q|
      total_score -= Question.find(q).value
    end
    total_score
  end

  def correct_answers
    self.answers.where(correct: true).pluck(:question_id)
  end

  def wrong_answers
    self.answers.where(correct: false).pluck(:question_id)
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    if current_user.answered?(params[:question_id])
      flash["alert"] = "Error. You've already answered this question."
    else
      q = Question.find(params[:question_id])
      # TODO fix answer handling, threshold is 3
      if Levenshtein.distance(params["answer"].downcase, q.answer.downcase) <= 3
        flash["success"] = "Correct. The answer was '#{q.answer}'. You gained #{q.value} points."
        a = current_user.answers.create(question_id: q.id, correct: true)
      else
        flash["error"] = "Incorrect. The answer was '#{q.answer}'. You lost #{q.value} points."
        a = current_user.answers.create(question_id: q.id, correct: false)
      end
    end
    redirect_to questions_path
  end

private
  def answer_params
    params.require(:answer).permit(:type, :answer, :question_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.generate_board(current_user.id)
  end

  def create
    if question_params["random"]
      q = Question.cache_random_question
      redirect_to q
    elsif question_params["category_id"]
      q = Question.where(category_id: question_params["category_id"]).sample
      redirect_to to q
    end
  end

  def show
    q = Question.find(params[:id])
    @question = q.question
    @value = q.value
    @category_title = q.category_title
    @airdate = q.airdate
  end

private
  def question_params
    params.permit(:category_id, :random)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @categories = Question.pluck(:category_title).uniq.shuffle.first(16)
  end

  def leaderboard
    User.find_each do |u|
      u.update(score: u.total_score)
    end
    @users = User.order(score: :desc).page(params[:page])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "success" then "alert alert-success"
      when "notice" then "alert alert-info"
      when "error" then "alert alert-warning"
      when "alert" then "alert alert-danger"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/answers/show.html.erb
<p>Question: <%= @q.question %></p>
<p>The answer was: <%= @q.answer %></p>
<p>Your total score is now: <%= @score %></p>

      <%= form_tag(questions_path, method: "post") do %>
        <input type="hidden" name="random">
        <%= submit_tag("Random") %>
      <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TriviaBot</title>
  <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/readable/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <!-- Static navbar -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= root_path %>>TriviaBot</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href=<%= home_path %>>Home</a></li>
            <li><a href=<%= questions_path %>>Question Board</a></li>
            <li><a href=<%= leaderboard_path %>>Leaderboard</a></li>
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
            <li><a href="#"><strong><%= "Your current score: #{current_user.total_score}" %></strong></a></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><a href=<%= new_user_session_path %>>Sign in</a></li>
            <li><a href=<%= new_user_registration_path %>>Register</a></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div><!--/.container-fluid -->
    </nav>
    <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %>"><%= value %></div>
    <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/questions/index.html.erb
<div class="page-header">
  <h1>Select a question: <small> Point value and category title is shown.</small></h1>
</div>
<% @questions.each_slice(4) do |qset| %>
<div class="row">
  <% qset.each do |q| %>
  
    <div class="col-xs-6 col-md-3">
      <div class="panel status panel-primary">
        <div class="panel-heading">
          <h1 class="panel-title text-center"><%= link_to "#{q.value}", question_path(q) %></h1>
        </div>
        <div class="panel-body text-center">                        
          <strong><%= link_to "#{q.category_title.titleize}", question_path(q) %></strong>
        </div>
      </div>
    </div>
  
  <% end %>
</div>
<% end %>

app/views/questions/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel status panel-primary">
        <div class="panel-heading">
          <h1 class="panel-title text-center"><%= @value %></h1>
        </div>
        <div class="panel-body text-center">                        
          <strong>Category: <%= @category_title.titleize %> &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp; Airdate: <%= @airdate %></strong>
        </div>
      </div>
      <blockquote>
        <p><%= @question %></p>
      </blockquote>
      <%= form_tag(answers_path, method: "POST") do %>
      <input type="text" class="form-control" name="answer" placeholder="Input your answer">
      <input type="hidden" name="question_id" value=<%= params[:id] %>>
      <button type="submit" class="btn btn-default">Submit</button>
      <% end %>
      <div class="profile-circle" style="background-color: rgba(0,0,0,.2);"></div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="page-header">
        <h2>Register to play!</h2>
        <h3>Sample of available trivia categories!</h3>
      </div>
      <table class="table table-hover table-bordered table-condensed">
      <% @categories.each_slice(4) do |cat| %>
        <tr>
          <% cat.each do |c| %>
          <td><%= c.titleize %></td>
          <% end %>
        </tr>
      <% end %>
    </div>
  </div>
</div>

app/views/static_pages/leaderboard.html.erb
<div class="container col-md-8 col-md-offset-2">
  <div class="page-header">
    <h1>Leaderboard <small> The IronYard's Finest </small></h1>
  </div>

  <table class="table table-hover table-bordered table-condensed">
    <tr>
      <th>Rank</th>
      <th>Username</th>
      <th>Score</th>
    </tr>
    <% if params[:page].nil? %>
      <% i = 0 %>
    <% else %>
      <% i = 10 * (params[:page].to_i - 10) %>
    <% end %>
    <% @users.each do |u| %>
      <% if current_user.id == u.id %>
    <tr class="info">
      <% else %>
    <tr>
      <% end %>
      <% i += 1 %>
      <td><%= i %></td>
      <td><%= u.email %></td>
      <td><%= u.total_score %></td>
    </tr>
    <% end %>
  </table>
  <%= paginate @users, theme: 'twitter-bootstrap-3' %>
</div>